apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: infrastructure
spec:
  plugin:
    crowdsec-bouncer:
      enabled: true
      logLevel: DEBUG
      crowdsecLapiScheme: http
      crowdsecLapiHost: crowdsec-service.infrastructure.svc.cluster.local:8080
      crowdsecLapiKey: "T/YmfWS9azSwgFl75UPB9ikgSkYH6du+rHhdhWE0n2A"
      forwardedHeadersTrustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
      clientTrustedIPs:
        - "10.0.0.0/8"
        - "172.16.0.0/12"
        - "192.168.0.0/16"
      crowdsecMode: live
      updateIntervalSeconds: 10
      defaultDecisionSeconds: 60
