apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: infrastructure
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 30s

      - name: Loki
        type: loki
        uid: P8E80F9AEF21F6940
        access: proxy
        url: http://loki:3100
        editable: false
        jsonData:
          maxLines: 1000
          timeout: 120

      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: Loki
          tracesToMetrics:
            datasourceUid: Prometheus
          serviceMap:
            datasourceUid: Prometheus

      - name: PostgreSQL-Infatium-Dev
        type: postgres
        uid: postgres-infatium-dev
        access: proxy
        url: postgres.infatium-dev.svc.cluster.local:5432
        user: grafana_reader
        editable: false
        jsonData:
          database: postgres
          sslmode: disable
          maxOpenConns: 5
          maxIdleConns: 2
          maxIdleConnsAuto: false
          connMaxLifetime: 14400
          postgresVersion: 1700
          timescaledb: false
        secureJsonData:
          password: $__env{GRAFANA_POSTGRES_PASSWORD}

