apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pvc-exporter
  namespace: infrastructure
  labels:
    app: pvc-exporter
    component: monitoring
spec:
  selector:
    matchLabels:
      app: pvc-exporter
  template:
    metadata:
      labels:
        app: pvc-exporter
        component: monitoring
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - name: pvc-collector
        image: alpine:latest
        command: ["/scripts/entrypoint.sh"]
        env:
        - name: COLLECTION_INTERVAL
          value: "1"
        volumeMounts:
        - name: k3s-storage
          mountPath: /host-storage
          readOnly: true
        - name: textfile-collector
          mountPath: /textfile-collector
        - name: scripts
          mountPath: /scripts
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
      volumes:
      - name: k3s-storage
        hostPath:
          path: /var/lib/rancher/k3s/storage
          type: Directory
      - name: textfile-collector
        hostPath:
          path: /var/lib/node_exporter/textfile_collector
          type: DirectoryOrCreate
      - name: scripts
        configMap:
          name: pvc-exporter-script
          defaultMode: 0755
      nodeSelector:
        node-role: infra
      tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule
