apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-registry-go
spec:
  template:
    spec:
      containers:
        - name: app-registry-go
          image: docker-registry.infrastructure:5000/go-registry:prod
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DATABASE_URL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "otel-collector.global.svc.cluster.local:4317"
            - name: GLITCHTIP_DSN
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SENTRY_DSN
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: AI_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: TELEGRAM_BOT_TOKEN
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-registry-go-config
data:
  ENVIRONMENT: "production"
  OTEL_ENVIRONMENT: "production"
