apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: infatium-prod
  labels:
    product: infatium
    environment: []
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 2000m
        memory: 4Gi
      min:
        cpu: 10m
        memory: 64Mi
      type: Container
    - max:
        cpu: 4000m
        memory: 8Gi
      min:
        cpu: 10m
        memory: 64Mi
      type: Pod
