apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-poller-go
spec:
  template:
    spec:
      containers:
        - name: worker-poller-go
          env:
            - name: GLITCHTIP_DSN
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SENTRY_DSN
            - name: ENVIRONMENT
              value: "production"
