apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-agents-python
spec:
  template:
    spec:
      containers:
        - name: worker-agents-python
          env:
            - name: PROXY_URL
              value: ""
            - name: PROXY_USERNAME
              value: ""
            - name: PROXY_PASSWORD
              value: ""
