apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-processor-go
spec:
  template:
    spec:
      containers:
        - name: worker-processor-go
          env:
            - name: GLITCHTIP_DSN
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SENTRY_DSN
            - name: ENVIRONMENT
              value: "production"
            - name: OTEL_ENVIRONMENT
              value: "production"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: REDIS_PASSWORD
