apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-init-schemas.sh: |
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        -- Create auth schema for JWT token storage (used by mobile app authentication)
        CREATE SCHEMA IF NOT EXISTS auth;

        -- Grant permissions on public schema
        GRANT USAGE ON SCHEMA public TO PUBLIC;
        GRANT CREATE ON SCHEMA public TO PUBLIC;
    EOSQL
