apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
