apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: infrastructure
spec:
  selector:
    app: docker-registry
  type: ClusterIP
  ports:
    - name: registry
      port: 5000
      targetPort: 5000
