apiVersion: v1
kind: Service
metadata:
  name: xray-ru-proxy
  namespace: infrastructure
spec:
  selector:
    app: xray-ru-proxy
  type: NodePort
  ports:
    - name: vless
      port: 10443
      targetPort: 10443
      nodePort: 31443
