apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-service-user
  labels:
    app: supabase-postgres
    service-type: infra
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 10
  template:
    metadata:
      labels:
        app: postgres-init-job
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h supabase-postgres -p 5432 -U supabase_admin; do
                echo "PostgreSQL unavailable - waiting..."
                sleep 2
              done
              echo "✅ PostgreSQL is ready"
      containers:
        - name: create-service-user
          image: postgres:15-alpine
          env:
            - name: PGHOST
              value: supabase-postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
            - name: SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: DATABASE_URL
          command:
            - sh
            - -c
            - |
              set -e

              echo "Extracting service user credentials..."

              # Parse postgresql+asyncpg://user:pass@host:port/db format
              SERVICE_USER=$(echo "$SERVICE_DATABASE_URL" | sed -n 's|.*://\([^:]*\):.*|\1|p')
              SERVICE_PASS=$(echo "$SERVICE_DATABASE_URL" | sed -n 's|.*://[^:]*:\([^@]*\)@.*|\1|p')

              if [ -z "$SERVICE_USER" ] || [ -z "$SERVICE_PASS" ]; then
                echo "❌ Failed to extract credentials from DATABASE_URL"
                exit 1
              fi

              echo "Service user: $SERVICE_USER"

              # Connect and create user
              export PGPASSWORD="$POSTGRES_PASSWORD"

              psql -U supabase_admin -d postgres <<-EOSQL
                DO \$\$
                DECLARE
                  user_exists BOOLEAN;
                BEGIN
                  SELECT EXISTS (SELECT FROM pg_roles WHERE rolname = '$SERVICE_USER') INTO user_exists;

                  IF NOT user_exists THEN
                    RAISE NOTICE 'Creating user: $SERVICE_USER';
                    CREATE ROLE $SERVICE_USER LOGIN PASSWORD '$SERVICE_PASS' CREATEROLE BYPASSRLS;

                    -- Grant database-level CREATE permission (for creating schemas like auth)
                    GRANT CREATE ON DATABASE postgres TO $SERVICE_USER;

                    -- Grant schema permissions (USAGE + CREATE for migrations)
                    GRANT USAGE, CREATE ON SCHEMA public TO $SERVICE_USER;
                    GRANT USAGE, CREATE ON SCHEMA auth TO $SERVICE_USER;

                    -- Grant privileges on existing objects
                    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $SERVICE_USER;

                    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA auth TO $SERVICE_USER;

                    -- Grant default privileges for future objects created by supabase_admin
                    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $SERVICE_USER;

                    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON FUNCTIONS TO $SERVICE_USER;

                    -- Grant default privileges for future objects created by supabase_auth_admin
                    ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON TABLES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON SEQUENCES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON FUNCTIONS TO $SERVICE_USER;

                    RAISE NOTICE '✅ User $SERVICE_USER created successfully with CREATE permission';
                  ELSE
                    RAISE NOTICE 'User $SERVICE_USER already exists, updating password and permissions';
                    ALTER ROLE $SERVICE_USER LOGIN PASSWORD '$SERVICE_PASS' CREATEROLE BYPASSRLS;

                    -- Grant database-level CREATE permission (for creating schemas like auth)
                    GRANT CREATE ON DATABASE postgres TO $SERVICE_USER;

                    -- Grant schema permissions (USAGE + CREATE for migrations)
                    GRANT USAGE, CREATE ON SCHEMA public TO $SERVICE_USER;
                    GRANT USAGE, CREATE ON SCHEMA auth TO $SERVICE_USER;

                    -- Grant privileges on existing objects
                    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $SERVICE_USER;

                    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO $SERVICE_USER;
                    GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA auth TO $SERVICE_USER;

                    -- Grant default privileges for future objects created by supabase_admin
                    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO $SERVICE_USER;

                    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON FUNCTIONS TO $SERVICE_USER;

                    -- Grant default privileges for future objects created by supabase_auth_admin
                    ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON TABLES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON SEQUENCES TO $SERVICE_USER;
                    ALTER DEFAULT PRIVILEGES FOR ROLE supabase_auth_admin IN SCHEMA auth GRANT ALL ON FUNCTIONS TO $SERVICE_USER;

                    RAISE NOTICE '✅ User $SERVICE_USER updated successfully with CREATE permission';
                  END IF;
                END \$\$;
              EOSQL

              echo "✅ Service user initialization completed"

              # Create postgres role (required by GoTrue v2.183.0+ migrations)
              echo "Creating postgres role for GoTrue migrations..."
              psql -U supabase_admin -d postgres <<-EOSQL
                DO \$\$
                BEGIN
                  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'postgres') THEN
                    CREATE ROLE postgres WITH SUPERUSER LOGIN PASSWORD '$POSTGRES_PASSWORD';
                    RAISE NOTICE '✅ postgres role created for GoTrue migrations';
                  ELSE
                    RAISE NOTICE 'postgres role already exists';
                  END IF;
                END \$\$;
              EOSQL

              # Verify user was created
              psql -U supabase_admin -d postgres -c "\du $SERVICE_USER"
