apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-init-users.sh: |
    #!/bin/bash
    set -e

    # Create authenticator role for PostgREST
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD '$POSTGRES_PASSWORD';

        CREATE ROLE anon NOLOGIN;
        GRANT anon TO authenticator;

        CREATE ROLE authenticated NOLOGIN;
        GRANT authenticated TO authenticator;

        CREATE ROLE service_role NOLOGIN BYPASSRLS;
        GRANT service_role TO authenticator;

        CREATE ROLE supabase_auth_admin NOINHERIT CREATEROLE CREATEDB LOGIN PASSWORD '$POSTGRES_PASSWORD';
        CREATE ROLE supabase_storage_admin NOINHERIT CREATEROLE LOGIN PASSWORD '$POSTGRES_PASSWORD';

        GRANT anon TO supabase_auth_admin;
        GRANT authenticated TO supabase_auth_admin;
        GRANT service_role TO supabase_auth_admin;

        GRANT anon TO supabase_storage_admin;
        GRANT authenticated TO supabase_storage_admin;
        GRANT service_role TO supabase_storage_admin;

        GRANT ALL PRIVILEGES ON DATABASE postgres TO supabase_auth_admin;
        GRANT ALL PRIVILEGES ON DATABASE postgres TO supabase_storage_admin;

        CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION supabase_auth_admin;
        CREATE SCHEMA IF NOT EXISTS storage AUTHORIZATION supabase_storage_admin;
        CREATE SCHEMA IF NOT EXISTS realtime;

        ALTER ROLE supabase_auth_admin SET search_path TO auth;
        ALTER ROLE supabase_storage_admin SET search_path TO storage;

        GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
        GRANT ALL ON SCHEMA public TO supabase_auth_admin, supabase_storage_admin;

        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
        ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO anon, authenticated, service_role;
    EOSQL
