apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-demo-user
  labels:
    app: supabase-postgres
    service-type: infra
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: postgres-init-job
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready..."
              until pg_isready -h supabase-postgres -p 5432 -U supabase_admin; do
                echo "PostgreSQL unavailable - waiting..."
                sleep 2
              done
              echo "✅ PostgreSQL is ready"
        - name: create-demo-user
          image: postgres:15-alpine
          env:
            - name: PGHOST
              value: supabase-postgres
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
          command:
            - sh
            - -c
            - |
              set -e

              export PGPASSWORD="$POSTGRES_PASSWORD"

              # Fixed UUID for demo user (must match DEMO_ACCOUNT_USER_ID in configmap)
              DEMO_USER_UUID="5b684a49-6f14-484c-ba99-fd6fc8a54f90"
              DEMO_USER_EMAIL="demo@infatium.ru"

              echo "Creating demo user for Apple App Review..."

              psql -U supabase_admin -d postgres <<-EOSQL
                DO \$\$
                DECLARE
                  user_exists BOOLEAN;
                BEGIN
                  SELECT EXISTS (
                    SELECT FROM auth.users WHERE email = '$DEMO_USER_EMAIL'
                  ) INTO user_exists;

                  IF NOT user_exists THEN
                    RAISE NOTICE 'Creating demo user: $DEMO_USER_EMAIL with UUID: $DEMO_USER_UUID';

                    -- Create user without password (password will be set via Admin API)
                    INSERT INTO auth.users (
                      instance_id,
                      id,
                      aud,
                      role,
                      email,
                      encrypted_password,
                      email_confirmed_at,
                      email_change,
                      email_change_token_new,
                      email_change_token_current,
                      confirmation_token,
                      recovery_token,
                      phone_change,
                      phone_change_token,
                      reauthentication_token,
                      raw_app_meta_data,
                      raw_user_meta_data,
                      created_at,
                      updated_at
                    ) VALUES (
                      '00000000-0000-0000-0000-000000000000',
                      '$DEMO_USER_UUID',
                      'authenticated',
                      'authenticated',
                      '$DEMO_USER_EMAIL',
                      '',
                      NOW(),
                      '',
                      '',
                      '',
                      '',
                      '',
                      '',
                      '',
                      '',
                      '{"provider": "email", "providers": ["email"], "is_demo_account": true}',
                      '{"name": "Demo User", "is_demo_account": true}',
                      NOW(),
                      NOW()
                    );

                    RAISE NOTICE '✅ Demo user created in database';
                  ELSE
                    RAISE NOTICE 'Demo user $DEMO_USER_EMAIL already exists';
                  END IF;
                END \$\$;
              EOSQL

              echo "✅ Demo user DB initialization completed"

              # Verify user was created
              psql -U supabase_admin -d postgres -c "SELECT id, email FROM auth.users WHERE email = '$DEMO_USER_EMAIL';"
      containers:
        - name: set-demo-password
          image: curlimages/curl:latest
          env:
            - name: SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: SERVICE_ROLE_KEY
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: API_EXTERNAL_URL
          command:
            - sh
            - -c
            - |
              set -e

              DEMO_USER_UUID="5b684a49-6f14-484c-ba99-fd6fc8a54f90"
              DEMO_PASSWORD="demo123456"

              echo "Waiting for Supabase Auth to be ready..."
              until curl -sf "http://supabase-auth:9999/health" > /dev/null 2>&1; do
                echo "Supabase Auth unavailable - waiting..."
                sleep 2
              done
              echo "✅ Supabase Auth is ready"

              echo "Setting password for demo user via Admin API..."

              # Set password via Supabase Admin API (ensures correct bcrypt format)
              HTTP_CODE=$(curl -s -o /tmp/response.txt -w "%{http_code}" \
                -X PUT "http://supabase-kong:8000/auth/v1/admin/users/$DEMO_USER_UUID" \
                -H "Content-Type: application/json" \
                -H "apikey: $SERVICE_ROLE_KEY" \
                -H "Authorization: Bearer $SERVICE_ROLE_KEY" \
                -d "{\"password\": \"$DEMO_PASSWORD\"}")

              if [ "$HTTP_CODE" = "200" ]; then
                echo "✅ Demo user password set successfully"
                cat /tmp/response.txt | head -c 200
                echo ""
              else
                echo "⚠️ Failed to set password (HTTP $HTTP_CODE), user may already have password"
                cat /tmp/response.txt
                echo ""
              fi

              echo "✅ Demo user initialization completed"
