apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-realtime
  labels:
    app: supabase-realtime
    service-type: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-realtime
  template:
    metadata:
      labels:
        app: supabase-realtime
    spec:
      containers:
        - name: realtime
          image: supabase/realtime:v2.25.35
          ports:
            - containerPort: 4000
              name: http
          envFrom:
            - secretRef:
                name: supabase-secrets
          env:
            - name: APP_NAME
              value: "realtime"
            - name: FLY_APP_NAME
              value: "realtime"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: SECRET_KEY_BASE
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: JWT_SECRET
            - name: DB_HOST
              value: supabase-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_AFTER_CONNECT_QUERY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: DB_AFTER_CONNECT_QUERY
            - name: DB_ENC_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: DB_ENC_KEY
          resources:
            requests:
              cpu: 15m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-realtime
  labels:
    app: supabase-realtime
spec:
  selector:
    app: supabase-realtime
  type: ClusterIP
  ports:
    - name: http
      port: 4000
      targetPort: 4000
