apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-rest
  labels:
    app: supabase-rest
    service-type: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-rest
  template:
    metadata:
      labels:
        app: supabase-rest
    spec:
      containers:
        - name: rest
          image: postgrest/postgrest:v11.2.2
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: PGRST_DB_URI
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: PGRST_DB_URI
            - name: PGRST_DB_SCHEMAS
              value: "public,storage,graphql_public"
            - name: PGRST_DB_ANON_ROLE
              value: "anon"
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: JWT_SECRET
            - name: PGRST_DB_USE_LEGACY_GUCS
              value: "false"
            - name: PGRST_APP_SETTINGS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: JWT_SECRET
            - name: PGRST_APP_SETTINGS_JWT_EXP
              value: "3600"
          envFrom:
            - secretRef:
                name: supabase-secrets
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-rest
  labels:
    app: supabase-rest
spec:
  selector:
    app: supabase-rest
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
