apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supabase-storage-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-storage
  labels:
    app: supabase-storage
    service-type: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-storage
  template:
    metadata:
      labels:
        app: supabase-storage
    spec:
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h supabase-postgres -p 5432 -U supabase_admin; do
                echo "PostgreSQL unavailable - sleeping"
                sleep 2
              done
              echo "PostgreSQL is ready!"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
      containers:
        - name: storage
          image: supabase/storage-api:v1.25.7
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - secretRef:
                name: supabase-secrets
          env:
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: ANON_KEY
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: SERVICE_ROLE_KEY
            - name: POSTGREST_URL
              value: "http://supabase-rest:3000"
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: JWT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: DATABASE_URL
            - name: DB_SEARCH_PATH
              value: "storage,public,extensions"
            - name: PGOPTIONS
              value: "-c search_path=storage,public,extensions"
            - name: DB_AFTER_CONNECT_QUERY
              value: "SET search_path TO storage,public,extensions"
            - name: FILE_SIZE_LIMIT
              value: "52428800"
            - name: STORAGE_BACKEND
              value: "file"
            - name: FILE_STORAGE_BACKEND_PATH
              value: "/var/lib/storage"
            - name: TENANT_ID
              value: "stub"
            - name: REGION
              value: "stub"
            - name: GLOBAL_S3_BUCKET
              value: "stub"
            - name: ENABLE_IMAGE_TRANSFORMATION
              value: "true"
            - name: IMGPROXY_URL
              value: "http://supabase-imgproxy:5001"
            - name: DB_INSTALL_ROLES
              value: "true"
            - name: DB_SUPER_USER
              value: "supabase_admin"
            - name: DB_ANON_ROLE
              value: "anon"
            - name: DB_SERVICE_ROLE
              value: "service_role"
            - name: DB_AUTHENTICATED_ROLE
              value: "authenticated"
          volumeMounts:
            - name: storage-data
              mountPath: /var/lib/storage
          resources:
            requests:
              cpu: 10m
              memory: 96Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /status
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: supabase-storage-data
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-storage
  labels:
    app: supabase-storage
spec:
  selector:
    app: supabase-storage
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
