apiVersion: batch/v1
kind: Job
metadata:
  name: storage-init-telegram-bucket
  labels:
    app: supabase-storage-init
    service-type: infra
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: supabase-storage-init
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      containers:
        - name: init-telegram-bucket
          image: postgres:15-alpine
          command:
            - sh
            - /scripts/init-telegram-bucket.sh
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: init-scripts
              mountPath: /scripts
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: init-scripts
          configMap:
            name: storage-init-scripts
            defaultMode: 0755
