apiVersion: apps/v1
kind: Deployment
metadata:
  name: supabase-studio
  labels:
    app: supabase-studio
    service-type: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supabase-studio
  template:
    metadata:
      labels:
        app: supabase-studio
    spec:
      containers:
        - name: studio
          image: supabase/studio:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: STUDIO_PG_META_URL
              value: "http://supabase-meta:8080"
            - name: SUPABASE_URL
              value: "https://supabase.infatium.ru"
            - name: SUPABASE_REST_URL
              value: "http://supabase-kong:8000/rest/v1"
            - name: SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: ANON_KEY
            - name: SUPABASE_SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: SERVICE_ROLE_KEY
            - name: SUPABASE_PUBLIC_URL
              value: "https://supabase.infatium.ru"
            - name: DEFAULT_ORGANIZATION_NAME
              value: "Default Organization"
            - name: DEFAULT_PROJECT_NAME
              value: "Default Project"
            - name: POSTGRES_HOST
              value: "supabase-postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: POSTGRES_PASSWORD
            - name: AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: DASHBOARD_USERNAME
            - name: AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: DASHBOARD_PASSWORD
          envFrom:
            - secretRef:
                name: supabase-secrets
          resources:
            requests:
              cpu: 10m
              memory: 192Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: supabase-studio
  labels:
    app: supabase-studio
spec:
  selector:
    app: supabase-studio
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
