apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-agents-python
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: worker-agents-python
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      metricRelabelings:
        - action: drop
          regex: _INBOX\..*
          sourceLabels: [messaging_destination_name]
        - action: drop
          regex: _INBOX\..*
          sourceLabels: [messaging_destination_publish_name]
