apiVersion: v1
kind: Secret
metadata:
  name: matomo-mariadb
  namespace: infrastructure
type: Opaque
stringData:
  root-password: "changeme-root-password"
  password: "changeme-matomo-password"
  database: "matomo"
  username: "matomo"
