apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-mariadb-data
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
