apiVersion: v1
kind: Service
metadata:
  name: matomo
  namespace: infrastructure
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: matomo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  namespace: infrastructure
  labels:
    app: matomo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matomo
  template:
    metadata:
      labels:
        app: matomo
        backup.infra/enabled: "true"
        backup.infra/type: "pvc"
    spec:
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      imagePullSecrets:
        - name: docker-registry-creds
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z matomo-mariadb 3306; do echo waiting for mariadb; sleep 2; done;']
        - name: configure-proxy
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              CONFIG_FILE="/var/www/html/config/config.ini.php"
              if [ -f "$CONFIG_FILE" ]; then
                if ! grep -q "proxy_client_headers" "$CONFIG_FILE"; then
                  echo "" >> "$CONFIG_FILE"
                  echo "; Proxy configuration for real IP detection" >> "$CONFIG_FILE"
                  echo "[General]" >> "$CONFIG_FILE"
                  echo 'proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"' >> "$CONFIG_FILE"
                  echo 'proxy_client_headers[] = "HTTP_X_REAL_IP"' >> "$CONFIG_FILE"
                  echo "assume_secure_protocol = 1" >> "$CONFIG_FILE"
                  echo "Proxy configuration added"
                else
                  echo "Proxy configuration already exists"
                fi
              else
                echo "Config file not found, will be created on first run"
              fi
          volumeMounts:
            - name: matomo-data
              mountPath: /var/www/html
      containers:
        - name: matomo
          image: matomo:5-apache
          ports:
            - containerPort: 80
              name: http
          env:
            - name: MATOMO_PROXY_CLIENT_HEADERS
              value: "HTTP_X_FORWARDED_FOR,HTTP_X_REAL_IP"
            - name: MATOMO_DATABASE_HOST
              value: matomo-mariadb
            - name: MATOMO_DATABASE_ADAPTER
              value: mysql
            - name: MATOMO_DATABASE_TABLES_PREFIX
              value: matomo_
            - name: MATOMO_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: matomo-mariadb
                  key: username
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matomo-mariadb
                  key: password
            - name: MATOMO_DATABASE_DBNAME
              valueFrom:
                secretKeyRef:
                  name: matomo-mariadb
                  key: database
            - name: PHP_MEMORY_LIMIT
              value: "512M"
          volumeMounts:
            - name: matomo-data
              mountPath: /var/www/html
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: matomo-data
          persistentVolumeClaim:
            claimName: matomo-data
