apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glitchtip-uploads
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
