apiVersion: apps/v1
kind: Deployment
metadata:
  name: glitchtip-web
  namespace: infrastructure
  labels:
    app: glitchtip-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glitchtip-web
  template:
    metadata:
      labels:
        app: glitchtip-web
    spec:
      nodeSelector:
        node-role: infra
      tolerations:
        - key: node-role
          operator: Equal
          value: infra
          effect: NoSchedule
      imagePullSecrets:
        - name: docker-registry-creds
      containers:
        - name: glitchtip
          image: registry.infra.makekod.ru/glitchtip-custom:v4.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: glitchtip-secrets
                  key: database-url
            - name: REDIS_URL
              value: "redis://glitchtip-redis:6379/0"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: glitchtip-secrets
                  key: secret-key
            - name: GLITCHTIP_DOMAIN
              value: "https://glitchtip.infra.makekod.ru"
            - name: DEFAULT_FROM_EMAIL
              value: "glitchtip@makekod.ru"
            - name: ENABLE_OPEN_USER_REGISTRATION
              value: "False"
            - name: GLITCHTIP_MAX_EVENT_LIFE_DAYS
              value: "90"
            - name: CELERY_WORKER_AUTOSCALE
              value: "1,3"
            - name: CELERY_WORKER_MAX_TASKS_PER_CHILD
              value: "10000"
          volumeMounts:
            - name: uploads
              mountPath: /code/uploads
          livenessProbe:
            httpGet:
              path: /_health/
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_health/
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: glitchtip-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: glitchtip-web
  namespace: infrastructure
spec:
  selector:
    app: glitchtip-web
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
