---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "{{ acme_email }}"
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: traefik
            podTemplate:
              spec:
                nodeSelector:
                  node-role: infra
                tolerations:
                  - key: node-role
                    operator: Equal
                    value: infra
                    effect: NoSchedule
