---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: infrastructure
spec:
  addresses:
    - "{{ metallb_ip_range }}"
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external
  namespace: infrastructure
spec:
  addresses:
    - "{{ infra_node_ip }}/32"
  autoAssign: false
