apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: infrastructure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backup-role
rules:
  # Read namespaces to discover all namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  # Read pods to find backup labels
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # Read secrets and configmaps for backup
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  # Read PVCs
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
  # Read services and ingresses for networking backup
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  # Exec into pods for database dumps and file copy
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  # Read deployments, statefulsets, and daemonsets for workloads backup
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backup-role-binding
subjects:
  - kind: ServiceAccount
    name: backup-sa
    namespace: infrastructure
roleRef:
  kind: ClusterRole
  name: backup-role
  apiGroup: rbac.authorization.k8s.io
